/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-03-25 00:34:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<!-- join.css를 사용하기위한 링크 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/join.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- css에 아이콘을 넣기위해서 링크추가 -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/d41dbe5e59.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- jQuery를 불러옵니다. -->\r\n");
      out.write("\r\n");
      out.write("<!-- member.js 유효성검사를 하기위한 스크립트 -->\r\n");
      out.write("<script src=\"script/member.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>join</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- 회원가입 폼 -->\r\n");
      out.write("\r\n");
      out.write("	<h1>회원가입</h1>\r\n");
      out.write("	<div class=\"joinTerms\">\r\n");
      out.write("		<p>서비스약관에 동의해주세요</p>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"\" class=\"checkForm\">\r\n");
      out.write("			<input type=\"checkbox\" id=\"allTerms\"> <label for=\"allTerms\">모두\r\n");
      out.write("				동의합니다.</label>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"termsBox\">\r\n");
      out.write("				<div class=\"\">\r\n");
      out.write("					<input type=\"checkbox\" id=\"check1\" class=\"termsCheck\"> <label\r\n");
      out.write("						for=\"check1\">[필수] 만 14세 이상입니다</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"checkbox\" id=\"check2\" class=\"termsCheck\"> <label\r\n");
      out.write("						for=\"check2\">[필수] 이용약관 동의</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"checkbox\" id=\"check3\" class=\"termsCheck\"> <label\r\n");
      out.write("						for=\"check3\">[필수] 전자금융거래 이용약관 동의</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"checkbox\" id=\"check4\" class=\"termsCheck\"> <label\r\n");
      out.write("						for=\"check4\">[필수] 개인정보 수집 및 이용 동의</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<input type=\"checkbox\" id=\"check5\" class=\"termsCheck\"> <label\r\n");
      out.write("						for=\"check5\">[필수] 개인정보 제공 동의</label>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input\r\n");
      out.write("				style=\"width: 100%; height: 100%; border-radius: 50px; margin-top: 20px;\"\r\n");
      out.write("				type=\"button\" value=\"뒤로 가기\" onclick=\"history.back()\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"joinWrap\" id=\"joinWrap\" style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("			<form action=\"OttServlet\" method=\"post\" id=\"joinForm\" name=\"frm\">\r\n");
      out.write("				<input type=\"hidden\" name=\"command\" value=\"member_insert\">\r\n");
      out.write("\r\n");
      out.write("				<p style=\"text-align: center;\">회원정보를 입력해주세요</p>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"joinBox\">\r\n");
      out.write("					<label for=\"email\"><i class=\"fa-regular fa-envelope\"></i></label> <input\r\n");
      out.write("						type=\"text\" name=\"email\" id=\"email\" placeholder=\"이메일\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"joinBox\">\r\n");
      out.write("					<label for=\"userid\"><i class=\"fa-solid fa-id-card\"></i></label> <input\r\n");
      out.write("						type=\"text\" name=\"userid\" id=\"userid\" placeholder=\"아이디\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"signbox\" style=\"text-align: center;\">\r\n");
      out.write("					<input style=\"margin-bottom: 10px\" type=\"button\" value=\"ID 중복 체크\"\r\n");
      out.write("						onclick=\"idCheck()\"> <input type=\"hidden\" name=\"reid\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"joinBox\">\r\n");
      out.write("					<label for=\"password\"><i class=\"fa-solid fa-lock\"></i></label> <input\r\n");
      out.write("						type=\"password\" name=\"pwd\" id=\"password\" placeholder='비밀번호'\r\n");
      out.write("						required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"joinBox\">\r\n");
      out.write("					<label for=\"passwordre\"><i class=\"fa-solid fa-lock\"></i></label> <input\r\n");
      out.write("						type=\"password\" name=\"pwd_check\" id=\"password\"\r\n");
      out.write("						placeholder='비밀번호재입력' required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"joinBox\">\r\n");
      out.write("					<label for=\"name\"><i class=\"fa-solid fa-user\"></i></label> <input\r\n");
      out.write("						type=\"text\" name=\"name\" id=\"name\" placeholder=\"이름\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"joinBox\">\r\n");
      out.write("					<label for=\"phone\"><i\r\n");
      out.write("						class=\"fa-solid fa-mobile-screen-button\"></i></label> <input type=\"text\"\r\n");
      out.write("						name=\"phone\" id=\"phone\" placeholder=\"휴대폰 번호\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"joinBox\">\r\n");
      out.write("					<label for=\"address\"><i class=\"fa-solid fa-map\"></i></label> \r\n");
      out.write("					<!-- <input type=\"text\" name=\"address\" id=\"address\" placeholder=\"주 소\" required> -->\r\n");
      out.write("					<input type=\"text\" name=\"address\" id=\"sample6_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("					<input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("					<input type=\"text\" id=\"sample6_address\" placeholder=\"주소\"><br>\r\n");
      out.write("					<input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\">\r\n");
      out.write("					<input type=\"text\" id=\"sample6_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"signbox\"\r\n");
      out.write("					style=\"text-align: center; margin-bottom: 20px; border-radius: 50px;\">\r\n");
      out.write("					<input type=\"submit\" class=\"fa-solid fa-mobile-screen-button\"\r\n");
      out.write("						value=\"S I G N U P\" onclick=\"return joinCheck()\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"signbox\"\r\n");
      out.write("					style=\"text-align: center; border-radius: 50px;\">\r\n");
      out.write("					<input type=\"submit\" class=\"fa-solid fa-mobile-screen-button\"\r\n");
      out.write("						value=\"뒤로 가기\" onclick=\"history.back()\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!--  전화번호 입력시 자동 (-)하이픈 처리 스크립트 -->\r\n");
      out.write("<script>\r\n");
      out.write("function autoHypenPhone(str){\r\n");
      out.write("    str = str.replace(/[^0-9]/g, '');\r\n");
      out.write("    var tmp = '';\r\n");
      out.write("    if( str.length < 4){\r\n");
      out.write("        return str;\r\n");
      out.write("    }else if(str.length < 7){\r\n");
      out.write("        tmp += str.substr(0, 3);\r\n");
      out.write("        tmp += '-';\r\n");
      out.write("        tmp += str.substr(3);\r\n");
      out.write("        return tmp;\r\n");
      out.write("    }else if(str.length < 11){\r\n");
      out.write("        tmp += str.substr(0, 3);\r\n");
      out.write("        tmp += '-';\r\n");
      out.write("        tmp += str.substr(3, 3);\r\n");
      out.write("        tmp += '-';\r\n");
      out.write("        tmp += str.substr(6);\r\n");
      out.write("        return tmp;\r\n");
      out.write("    }else{              \r\n");
      out.write("        tmp += str.substr(0, 3);\r\n");
      out.write("        tmp += '-';\r\n");
      out.write("        tmp += str.substr(3, 4);\r\n");
      out.write("        tmp += '-';\r\n");
      out.write("        tmp += str.substr(7);\r\n");
      out.write("        return tmp;\r\n");
      out.write("    }\r\n");
      out.write("    return str;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var cellPhone = document.getElementById('phone');\r\n");
      out.write("cellPhone.onkeyup = function(event){\r\n");
      out.write("event = event || window.event;\r\n");
      out.write("var _val = this.value.trim();\r\n");
      out.write("this.value = autoHypenPhone(_val) ;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 약관동의를 모두선택할경우 회원가입폼이 출력되는 스크립트 -->\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    $('#allTerms').click(function(){\r\n");
      out.write("        var checked = $(this).is(':checked');\r\n");
      out.write("\r\n");
      out.write("        if(checked){\r\n");
      out.write("            $('.termsCheck').prop('checked', true);\r\n");
      out.write("            $('#joinWrap').show(); // 회원가입 양식을 보여줍니다.\r\n");
      out.write("            $('.joinTerms').hide(); // 약관 동의란을 숨깁니다.\r\n");
      out.write("        }else {\r\n");
      out.write("            $('.termsCheck').prop('checked', false);\r\n");
      out.write("            $('#joinWrap').hide(); // 회원가입 양식을 숨깁니다.\r\n");
      out.write("            $('.joinTerms').show(); // 약관 동의란을 보여줍니다.\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.termsCheck').click(function(){\r\n");
      out.write("        var terms = $('.termsCheck');\r\n");
      out.write("        var flag = true;\r\n");
      out.write("\r\n");
      out.write("        for(var input of terms){\r\n");
      out.write("            if (!input.checked) {\r\n");
      out.write("                flag = false;\r\n");
      out.write("                break; // 하나라도 체크되어 있지 않으면 루프를 종료합니다.\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if(flag){\r\n");
      out.write("            $('#allTerms').prop('checked', true);\r\n");
      out.write("            $('#joinWrap').show(); // 회원가입 양식을 보여줍니다.\r\n");
      out.write("            $('.joinTerms').hide(); // 약관 동의란을 숨깁니다.\r\n");
      out.write("        }else {\r\n");
      out.write("            $('#allTerms').prop('checked', false);\r\n");
      out.write("            $('#joinWrap').hide(); // 회원가입 양식을 숨깁니다.\r\n");
      out.write("            $('.joinTerms').show(); // 약관 동의란을 보여줍니다.\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function sample6_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"sample6_detailAddress\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
